import React, { useMemo, useState } from "react";
import { useSettings } from "../SettingsContext";
import { useDql } from "../useDql";
import { webAppSummaryQuery, webVitalsPerAppQuery } from "../queries";
import { computeAppScore } from "../scoring";
import { gradeFromScore } from "../components/GradeBadge";
import { SectionCard, fmt } from "../components/layout";

// ---------------------------------------------------------------------------
// Action Backlog — cross-app, prioritised list of recommended actions.
// Each action is data-driven: generated by evaluating every app against
// known performance thresholds, then sorted by traffic-weighted impact.
// ---------------------------------------------------------------------------

const GREEN  = "#0D9C29";
const YELLOW = "#F9A825";
const ORANGE = "#FB8C00";
const RED    = "#C21930";
const BLUE   = "#4589FF";

type Impact = "high" | "medium" | "low";
type Category = "Performance" | "Reliability" | "Core Web Vitals" | "Engagement";

interface Action {
  id: string;
  application: string;
  sessions: number;
  score: number;
  impact: Impact;
  category: Category;
  metric: string;
  value: string;
  threshold: string;
  recommendation: string;
  urgencyScore: number; // sessions × severity, used for sort
}

function impactColor(impact: Impact) {
  if (impact === "high")   return RED;
  if (impact === "medium") return ORANGE;
  return "rgba(128,128,128,0.7)";
}

function categoryColor(cat: Category) {
  if (cat === "Core Web Vitals") return BLUE;
  if (cat === "Reliability")     return RED;
  if (cat === "Performance")     return YELLOW;
  return GREEN;
}

export const ActionBacklogTab: React.FC = () => {
  const { timeframeDays, webAppFilter, gradeWeights } = useSettings();
  const sel = webAppFilter.selected;

  const sum    = useDql(webAppSummaryQuery(timeframeDays, sel),    [timeframeDays, sel]);
  const vitals = useDql(webVitalsPerAppQuery(timeframeDays, sel),  [timeframeDays, sel]);

  const [filterImpact, setFilterImpact] = useState<Impact | "all">("all");
  const [filterCategory, setFilterCategory] = useState<Category | "all">("all");
  const [filterApp, setFilterApp] = useState<string>("");

  const actions = useMemo((): Action[] => {
    const vByApp: Record<string, any> = {};
    (vitals.data?.records ?? []).forEach((r: any) => { vByApp[String(r.application ?? "")] = r; });

    const out: Action[] = [];
    const sumRecords = sum.data?.records ?? [];

    for (const r of sumRecords as any[]) {
      const app = String(r.application ?? "");
      if (!app) continue;
      const v = vByApp[app] || {};
      const sessions  = Number(r.sessions   ?? 0);
      const actions_  = Number(r.actions    ?? 0);
      const errors    = Number(r.errors     ?? 0);
      const avgDur    = Number(r.avgDuration ?? NaN);
      const apdex     = Number(r.apdex      ?? NaN);
      const errorRate = Number(r.errorRate  ?? NaN);
      const sat       = Number(r.satisfied  ?? 0);
      const tol       = Number(r.tolerating ?? 0);
      const fru       = Number(r.frustrated ?? 0);
      const lcp  = Number(v.lcpAvg  ?? NaN);
      const inp  = Number(v.inpAvg  ?? NaN);
      const cls  = Number(v.clsAvg  ?? NaN);
      const ttfb = Number(v.ttfbAvg ?? NaN);

      const summary   = { application: app, sessions, users: sessions, actions: actions_, errors, avgDuration: avgDur, apdex, satisfied: sat, tolerating: tol, frustrated: fru, errorRate, bounceRate: 0, newUsers: 0, bounces: 0 };
      const vitalsRow = { application: app, lcpAvg: lcp, inpAvg: inp, clsAvg: cls, ttfbAvg: ttfb, fcpAvg: NaN, loadEndAvg: NaN };
      const { score } = computeAppScore(vitalsRow, summary, gradeWeights);

      const log = Math.log10(Math.max(10, sessions));
      const add = (partial: Omit<Action, "id" | "application" | "sessions" | "score" | "urgencyScore">, severity: number) => {
        out.push({ ...partial, id: `${app}-${partial.metric}`, application: app, sessions, score, urgencyScore: log * severity });
      };

      // ------------------------------------------------------------------
      // Core Web Vitals
      if (isFinite(lcp)) {
        if (lcp > 4000) add({ impact: "high", category: "Core Web Vitals", metric: "LCP", value: fmt.ms(lcp), threshold: "≤ 2,500ms (Good)", recommendation: `LCP is ${fmt.ms(lcp)} — in the "Poor" range. Preload the hero image, reduce render-blocking resources, and serve assets via CDN to cut paint time.` }, 3);
        else if (lcp > 2500) add({ impact: "medium", category: "Core Web Vitals", metric: "LCP", value: fmt.ms(lcp), threshold: "≤ 2,500ms (Good)", recommendation: `LCP is ${fmt.ms(lcp)} — "Needs Improvement". Compress images, eliminate unused CSS above the fold, and consider lazy-loading below-fold content.` }, 1.5);
      }
      if (isFinite(inp)) {
        if (inp > 500) add({ impact: "high", category: "Core Web Vitals", metric: "INP", value: fmt.ms(inp), threshold: "≤ 200ms (Good)", recommendation: `INP is ${fmt.ms(inp)} — severely delayed interactions. Break up long tasks, defer non-critical JS, and move heavy work to web workers.` }, 3);
        else if (inp > 200) add({ impact: "medium", category: "Core Web Vitals", metric: "INP", value: fmt.ms(inp), threshold: "≤ 200ms (Good)", recommendation: `INP is ${fmt.ms(inp)} — interactions feel sluggish. Audit event handlers for synchronous DOM operations and minimise main-thread blocking.` }, 1.5);
      }
      if (isFinite(cls)) {
        if (cls > 0.25) add({ impact: "high", category: "Core Web Vitals", metric: "CLS", value: cls.toFixed(3), threshold: "≤ 0.1 (Good)", recommendation: `CLS is ${cls.toFixed(3)} — severe layout instability. Set explicit width/height on images/embeds, avoid inserting content above existing elements, and preload fonts.` }, 2.5);
        else if (cls > 0.1) add({ impact: "medium", category: "Core Web Vitals", metric: "CLS", value: cls.toFixed(3), threshold: "≤ 0.1 (Good)", recommendation: `CLS is ${cls.toFixed(3)} — noticeable layout shift. Reserve space for dynamic content (ads, banners) and ensure fonts don't cause FOUT/FOIT.` }, 1.2);
      }
      if (isFinite(ttfb)) {
        if (ttfb > 1800) add({ impact: "high", category: "Core Web Vitals", metric: "TTFB", value: fmt.ms(ttfb), threshold: "≤ 800ms (Good)", recommendation: `TTFB is ${fmt.ms(ttfb)} — slow server response. Review origin server performance, enable HTTP/2, add server-side caching, and consider a CDN for initial HTML.` }, 2.5);
        else if (ttfb > 800) add({ impact: "medium", category: "Core Web Vitals", metric: "TTFB", value: fmt.ms(ttfb), threshold: "≤ 800ms (Good)", recommendation: `TTFB is ${fmt.ms(ttfb)} — server latency is above the Good threshold. Enable connection keep-alive, reduce DNS lookup time, and optimise server-side rendering.` }, 1.2);
      }

      // ------------------------------------------------------------------
      // Reliability
      if (isFinite(errorRate)) {
        if (errorRate > 5) add({ impact: "high", category: "Reliability", metric: "Error rate", value: fmt.pct(errorRate), threshold: "< 1%", recommendation: `Error rate is ${fmt.pct(errorRate)} — ${Math.round(errors).toLocaleString()} errors this period. Go to the Errors tab, identify the top JS error type, and fix or suppress it urgently.` }, 4);
        else if (errorRate > 1) add({ impact: "medium", category: "Reliability", metric: "Error rate", value: fmt.pct(errorRate), threshold: "< 1%", recommendation: `Error rate is ${fmt.pct(errorRate)} — above the 1% healthy baseline. Triage the Errors tab for recurring patterns and ensure error boundaries are in place.` }, 2);
      }

      // ------------------------------------------------------------------
      // Performance (Apdex / load time)
      if (isFinite(apdex)) {
        const sfDen = sat + tol + fru;
        const fruPct = sfDen > 0 ? (fru / sfDen) * 100 : 0;
        if (apdex < 0.5) add({ impact: "high", category: "Performance", metric: "Apdex", value: apdex.toFixed(2), threshold: "≥ 0.85 (Good)", recommendation: `Apdex is ${apdex.toFixed(2)} — unacceptable user satisfaction. ${fruPct.toFixed(0)}% of actions are frustrated (>12s). Identify the slowest user actions in Hyperlyzer and eliminate blocking operations.` }, 3.5);
        else if (apdex < 0.7) add({ impact: "medium", category: "Performance", metric: "Apdex", value: apdex.toFixed(2), threshold: "≥ 0.85 (Good)", recommendation: `Apdex is ${apdex.toFixed(2)} — poor user satisfaction. Focus on reducing frustrated action count (${fruPct.toFixed(0)}% of interactions). Use the Hyperlyzer tab to isolate the worst-performing pages.` }, 2);
        else if (apdex < 0.85) add({ impact: "low", category: "Performance", metric: "Apdex", value: apdex.toFixed(2), threshold: "≥ 0.85 (Good)", recommendation: `Apdex is ${apdex.toFixed(2)} — needs improvement. Review p90 action durations and target long-tail slowness to push satisfaction from "Fair" to "Good".` }, 0.8);
      }
      if (isFinite(avgDur) && avgDur > 6000) {
        add({ impact: "high", category: "Performance", metric: "Avg load time", value: fmt.ms(avgDur), threshold: "< 3,000ms", recommendation: `Average action duration is ${fmt.ms(avgDur)} — well above the 3s threshold. Profile the heaviest pages in Hyperlyzer and look for synchronous network calls or blocking scripts.` }, 2.5);
      } else if (isFinite(avgDur) && avgDur > 3000) {
        add({ impact: "low", category: "Performance", metric: "Avg load time", value: fmt.ms(avgDur), threshold: "< 3,000ms", recommendation: `Average action duration is ${fmt.ms(avgDur)} — above target. Review the slowest user actions for deferred loading opportunities.` }, 0.8);
      }
    }

    return out.sort((a, b) => b.urgencyScore - a.urgencyScore);
  }, [sum.data, vitals.data, gradeWeights]);

  const filtered = useMemo(() => actions.filter(a => {
    if (filterImpact !== "all" && a.impact !== filterImpact) return false;
    if (filterCategory !== "all" && a.category !== filterCategory) return false;
    if (filterApp && !a.application.toLowerCase().includes(filterApp.toLowerCase())) return false;
    return true;
  }), [actions, filterImpact, filterCategory, filterApp]);

  const counts = useMemo(() => ({
    high:   actions.filter(a => a.impact === "high").length,
    medium: actions.filter(a => a.impact === "medium").length,
    low:    actions.filter(a => a.impact === "low").length,
    apps:   new Set(actions.map(a => a.application)).size,
  }), [actions]);

  const loading = sum.loading || vitals.loading;

  return (
    <div>
      {/* Header */}
      <div style={{ padding: "20px 20px 0" }}>
        <div style={{ fontSize: 20, fontWeight: 800, letterSpacing: 0.2 }}>Action Backlog</div>
        <div style={{ fontSize: 12, opacity: 0.65, marginTop: 2 }}>
          Data-driven, cross-app list of recommended actions — ranked by traffic × metric severity.
        </div>
      </div>

      {/* Summary KPIs */}
      <div style={{ display: "flex", gap: 10, padding: "14px 20px 0", flexWrap: "wrap" }}>
        {[
          { label: "High impact", value: counts.high,   color: RED    },
          { label: "Medium",      value: counts.medium, color: ORANGE },
          { label: "Low",         value: counts.low,    color: "rgba(128,128,128,0.7)" },
          { label: "Apps affected", value: counts.apps, color: BLUE   },
        ].map(k => (
          <div key={k.label} style={{ padding: "10px 16px", borderRadius: 8, background: "rgba(128,128,128,0.06)", border: `1px solid ${k.color}30`, minWidth: 110, flex: "1 1 110px" }}>
            <div style={{ fontSize: 11, opacity: 0.55 }}>{k.label}</div>
            <div style={{ fontSize: 26, fontWeight: 800, color: k.color }}>{loading ? "…" : k.value}</div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div style={{ display: "flex", gap: 10, padding: "12px 20px 0", flexWrap: "wrap", alignItems: "center" }}>
        <span style={{ fontSize: 12, opacity: 0.6 }}>Filter:</span>
        {/* Impact */}
        {(["all", "high", "medium", "low"] as const).map(v => (
          <button
            key={v}
            onClick={() => setFilterImpact(v)}
            style={{
              fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 12, cursor: "pointer",
              background: filterImpact === v ? (v === "high" ? RED : v === "medium" ? ORANGE : v === "low" ? "rgba(128,128,128,0.5)" : BLUE) : "rgba(128,128,128,0.1)",
              color: filterImpact === v ? "#fff" : "inherit",
              border: "1px solid rgba(128,128,128,0.25)",
            }}
          >
            {v === "all" ? "All impact" : v.charAt(0).toUpperCase() + v.slice(1)}
          </button>
        ))}
        {/* Category */}
        {(["all", "Core Web Vitals", "Reliability", "Performance"] as const).map(v => (
          <button
            key={v}
            onClick={() => setFilterCategory(v as any)}
            style={{
              fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 12, cursor: "pointer",
              background: filterCategory === v ? categoryColor(v as Category) : "rgba(128,128,128,0.1)",
              color: filterCategory === v ? "#fff" : "inherit",
              border: "1px solid rgba(128,128,128,0.25)",
            }}
          >
            {v}
          </button>
        ))}
        {/* App search */}
        <input
          type="text"
          value={filterApp}
          onChange={e => setFilterApp(e.target.value)}
          placeholder="filter by app…"
          style={{ fontSize: 11, padding: "3px 8px", borderRadius: 4, border: "1px solid rgba(128,128,128,0.3)", background: "rgba(255,255,255,0.05)", color: "inherit", outline: "none", width: 130 }}
        />
        {filtered.length !== actions.length && (
          <span style={{ fontSize: 11, opacity: 0.5 }}>{filtered.length} of {actions.length} actions</span>
        )}
      </div>

      {/* Action list */}
      <div style={{ padding: "12px 20px 20px" }}>
        {loading ? (
          <div style={{ padding: 40, textAlign: "center", opacity: 0.5 }}>Loading…</div>
        ) : filtered.length === 0 ? (
          <div style={{ padding: 40, textAlign: "center", opacity: 0.5 }}>
            {actions.length === 0 ? "No actions — all apps are within healthy thresholds." : "No actions match current filters."}
          </div>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {filtered.map((a, idx) => {
              const g = gradeFromScore(a.score);
              return (
                <div
                  key={a.id}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "28px 36px 1fr auto auto",
                    gap: "0 12px",
                    alignItems: "center",
                    padding: "10px 14px",
                    borderRadius: 8,
                    background: "rgba(128,128,128,0.04)",
                    border: `1px solid ${impactColor(a.impact)}28`,
                    borderLeft: `3px solid ${impactColor(a.impact)}`,
                  }}
                >
                  {/* Rank */}
                  <div style={{ fontSize: 10, opacity: 0.35, fontFamily: "monospace", textAlign: "center" }}>#{idx + 1}</div>
                  {/* App grade */}
                  <div style={{ fontSize: 20, fontWeight: 900, color: g.color, textAlign: "center" }}>{g.letter}</div>
                  {/* Body */}
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 3, flexWrap: "wrap" }}>
                      <span style={{ fontSize: 12, fontWeight: 700, opacity: 0.9 }}>{a.application}</span>
                      <span style={{ fontSize: 10, fontWeight: 700, padding: "1px 6px", borderRadius: 3, background: `${impactColor(a.impact)}18`, color: impactColor(a.impact), textTransform: "uppercase" }}>{a.impact}</span>
                      <span style={{ fontSize: 10, fontWeight: 600, padding: "1px 6px", borderRadius: 3, background: `${categoryColor(a.category)}15`, color: categoryColor(a.category) }}>{a.category}</span>
                      <span style={{ fontSize: 11, fontFamily: "monospace", opacity: 0.7 }}>
                        {a.metric}: <strong style={{ color: impactColor(a.impact) }}>{a.value}</strong>
                        <span style={{ opacity: 0.5 }}> (target {a.threshold})</span>
                      </span>
                    </div>
                    <div style={{ fontSize: 12, opacity: 0.8, lineHeight: 1.4 }}>{a.recommendation}</div>
                  </div>
                  {/* Sessions */}
                  <div style={{ fontSize: 10, opacity: 0.45, textAlign: "right", minWidth: 64 }}>
                    <div>{fmt.num(a.sessions)}</div>
                    <div>sessions</div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};
